-- Bronze database and schema setup for inbound leads analytics.
-- Run as a role with privileges to create database, schemas, and tables.

CREATE DATABASE IF NOT EXISTS INBOUND_LEADS;

USE DATABASE INBOUND_LEADS;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS DBT_DEV;

USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS LEADS_RAW (
    RAW_DATA VARIANT,
    SOURCE_FILE_NAME STRING,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_DATE DATE,
    INSERT_DATE TIMESTAMP_NTZ,
    BRONZE_LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LEAD_ACTIVITIES_RAW (
    RAW_DATA VARIANT,
    SOURCE_FILE_NAME STRING,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_DATE DATE,
    INSERT_DATE TIMESTAMP_NTZ,
    BRONZE_LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CUSTOM_ACTIVITIES_RAW (
    RAW_DATA VARIANT,
    SOURCE_FILE_NAME STRING,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_DATE DATE,
    INSERT_DATE TIMESTAMP_NTZ,
    BRONZE_LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CLOSE_CRM_USERS_RAW (
    RAW_DATA VARIANT,
    SOURCE_FILE_NAME STRING,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_DATE DATE,
    INSERT_DATE TIMESTAMP_NTZ,
    BRONZE_LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
