-- Bronze external stage and JSON file format.
-- Replace the S3 URL and storage integration before running.

USE DATABASE INBOUND_LEADS;
USE SCHEMA BRONZE;

CREATE FILE FORMAT IF NOT EXISTS JSON_LANDING_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE
    IGNORE_UTF8_ERRORS = TRUE
    COMPRESSION = AUTO;

CREATE OR REPLACE STORAGE INTEGRATION STORINT_AWS_419022_01
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<YOUR-AWS-ACCOUNT>:role/<YOUR-ROLE-FOR-SNOWFLAKE>'
  STORAGE_ALLOWED_LOCATIONS = ( 's3://<YOUR-BUCKET-NAME>/inbound-leads/raw/',
                              ) ;
                              
DESC INTEGRATION STORINT_AWS_419022_01;
SHOW INTEGRATIONS;

CREATE STAGE IF NOT EXISTS S3_RAW_LANDING_STAGE
    URL = 's3://YOUR-BUCKET/inbound-leads/raw/'
    STORAGE_INTEGRATION = YOUR_STORAGE_INTEGRATION
    FILE_FORMAT = JSON_LANDING_FORMAT;

-- Optional validation after setup:
LIST @S3_RAW_LANDING_STAGE;
